export type TocItem = { depth: number; text: string; id: string }
export type Post = { slug: string; title: string; date: string; categories: string[]; tags: string[]; excerpt: string; html: string; toc?: TocItem[] }
export type PracticeStatus = '熟练掌握' | '正在练习' | '曾经熟悉' | '准备练习'
export type Song = { id: number; title: string; artist: string; tags: string[]; practiceStatus: PracticeStatus; addedAt: string; color: string; note?: string; album?: string; releaseDate?: string; coverUrl?: string; neteaseId?: number; neteaseUrl?: string }
export type MusicReview = { songId: number; createdAt: string; content: string }
export type MusicLibrary = { updatedAt: string; songs: Song[]; reviews: MusicReview[] }
export type MemoryEntry = { date: string; content: string; images: string[] }
export type MemoryLog = { updatedAt: string; entries: MemoryEntry[] }
export type BlogSection = 'posts' | 'categories' | 'archives'
export type View = { kind: 'home' | 'blog' | 'tags' | 'about' | 'music' | 'media' | 'memory' | 'post'; slug?: string; anchor?: string; section?: BlogSection }
