export type TocItem = { depth: number; text: string; id: string }
export type Post = { slug: string; title: string; date: string; categories: string[]; tags: string[]; excerpt: string; html: string; toc?: TocItem[] }
export type MusicCategory = 'J-Pop' | 'Anisong' | '术力口' | '二偶'
export type PracticeStatus = '熟练掌握' | '正在练习' | '曾经熟悉' | '准备练习'
export type Song = { id: string; title: string; artist: string; category: MusicCategory; practiceStatus: PracticeStatus; addedAt: string; color: string; note?: string; youtubeId?: string; searchUrl?: string }
export type MusicThought = { id: string; songId: string; date: string; mood: string; content: string }
export type MusicLibrary = { updatedAt: string; songs: Song[]; thoughts: MusicThought[] }
export type NeteaseSong = { id: number; name: string; artists: string; album: string; coverUrl?: string }
export type View = { kind: 'home' | 'categories' | 'archives' | 'tags' | 'about' | 'music' | 'post'; slug?: string; anchor?: string }
